### PR TITLE
fix: send smsCodeMatcher for getSmsCode

### PR DESCRIPTION
**Pull request by andrelmlins**
Hi guys, great project. I verified that the 'smsCodeMatcher' was not being sent and made the correction.

### CODE REVIEW

**Comment by Tkko** [comment]
Hi @andrelmlins thanks for the PR
Just one more thing, could you also make `smsCodeMatcher` non nullable as SmartAuth doesn't accept nullable matcher

https://github.com/Tkko/Flutter_Pinput/blob/a6a02f39017a16ee8a4312cb332d60847bfd2130/lib/src/pinput.dart#L136

**Comment by andrelmlins** [comment]
Hi @Tkko , change made

**Comment by andrelmlins** [comment]
@Tkko would it be possible to generate a new version today?

**Comment by Tkko** [comment]
@andrelmlins version 2.2.11 is uploaded

**Pull request merged**
